services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: k12_rnd_backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - qdrant
    environment:
      - POSTGRES_HOST=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: k12_rnd_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrantdata:/qdrant/storage

volumes:
  pgdata:
  qdrantdata:
